spring.application.name=ms-core
spring.datasource.url=jdbc:postgresql://localhost:5432/corebank_db
spring.datasource.username=corebank
spring.datasource.password=corebank123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true